---
# The path to the all.yml file on the target-server.
all_yml_path: "{{ ansible_user_dir }}/inventory/group_vars/all.yml"
# The path to the all.yml.cfg (all.yml override) file on the target-server.
all_yml_cfg_path: "{{ ansible_user_dir }}/inventory/group_vars/all.yml.cfg"
# The path to the OSEv3.yml file on the target-server.
osev3_yml_path: "{{ ansible_user_dir }}/inventory/group_vars/OSEv3.yml"
# The path to the OSEv3.yml.cfg (OSEv3.yml override) file on the target-server.
osev3_yml_cfg_path: "{{ ansible_user_dir }}/inventory/group_vars/OSEv3.yml.cfg"
# The path to the file that contains the name server update information.
nsupdate_file: "{{ lookup('env', 'nsupdate_file')|default(ansible_user_dir ~ '/nsupdate_keys.yml', true) }}"
# Look up the environment variable with a space separated string of image registry servers to add to the container configuration.
openshift_registries: "{{ lookup('env', 'openshift_registries') }}"
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
# Break up the space separate string into a list of image registries for the OSEv3.yml variables.
registries: "{{ openshift_registries.split(' ') }}"
