---
# A list of regular expressions to search and replace in openshift-ansible all.yml.
all_yml:
  - { find: "^openshift_openstack_clusterid.*", replace: "openshift_openstack_clusterid: \"{{ openshift_env_id }}\"" }
  - { find: "^openshift_openstack_dns_nameservers:.*", replace: "openshift_openstack_dns_nameservers: [{{ public_dns_nameservers }}]" }
  - { find: "^openshift_openstack_keypair_name.*", replace: "openshift_openstack_keypair_name: \"{{ openstack_keypair_name }}\"" }
  - { find: "^openshift_openstack_external_network_name.*", replace: "openshift_openstack_external_network_name: \"{{ openstack_public_network_name }}\"" }
  - { find: "^openshift_openstack_default_image_name.*", replace: "openshift_openstack_default_image_name: \"{{ virtual_image_name }}\"" }
  - { find: "^openshift_openstack_num_masters.*", replace: "openshift_openstack_num_masters: 3" }
  - { find: "^openshift_openstack_num_infra.*", replace: "openshift_openstack_num_infra: 3" }
  - { find: "^openshift_openstack_num_cns.*", replace: "openshift_openstack_num_cns: 0" }	# 3 to enable cns
  - { find: "^#openshift_openstack_master_flavor:.*", replace: "openshift_openstack_master_flavor: \"master_etcd\"" }
  - { find: "^#openshift_openstack_infra_flavor:.*", replace: "openshift_openstack_infra_flavor: \"infra_elastic\"" }
  - { find: "^#openshift_openstack_cns_flavor:.*", replace: "openshift_openstack_cns_flavor: \"m4.large-pci\"" }
  - { find: "^#openshift_openstack_node_flavor.*", replace: "openshift_openstack_node_flavor: \"node_medium\"" }
  - { find: "^#openshift_openstack_lb_flavor:.*", replace: "openshift_openstack_lb_flavor: \"load_balancer\"" }
  - { find: "^openshift_openstack_default_flavor:.*", replace: "openshift_openstack_default_flavor: \"m1.medium\"" }
  # - { find: "^#manage_packages.*", replace: "manage_packages: false"}
  # Use VM storage only, no Cinder at this time.
  - { find: "^# openshift_openstack_ephemeral_volumes.*", replace: "openshift_openstack_ephemeral_volumes: true"}
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
# A list of regular expressions to search and replace in the openshift-ansible OSEv3.yml.
osev3_yml:
  - { find: "^openshift_deployment_type: origin", replace: "#openshift_deployment_type: origin" }
  - { find: "^#openshift_deployment_type: openshift-enterprise", replace: "openshift_deployment_type: openshift-enterprise" }
  - { find: "^openshift_master_default_subdomain.*", replace: "openshift_master_default_subdomain: 'router.default.svc.cluster.local'" }
  # - { find: "^#openshift_cloudprovider_kind.*", replace: "openshift_cloudprovider_kind: openstack"}
# Look for a space separated string of time servers from an environment variable.
time_servers: "{{ lookup('env', 'time_servers')|default('0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org', true) }}"
# Break up the space separated string into a list of time servers.
time_servers_list: "{{ time_servers.split(' ') }}"
