---
# The path to the all.yml file on the target-server.
all_yml_path: "{{ ansible_user_dir }}/inventory/group_vars/all.yml"
# The size of blocks to scale up.
block_size: "{{ lookup('env', 'scale_block_size') | default('100', true) }}"
# The algorithm to use when creating the DNS update key.
dns_key_algorithm: "{{ lookup('env', 'dns_key_algorithm')|default('hmac-md5', true) }}"
# The DNS update key file name.
dns_key_file: "{{ lookup('env', 'dns_update_file')|default('dns_update.key', true) }}"
# The key name when creating the DNS update key.
dns_key_name: "{{ lookup('env', 'dns_key_name')|default('update-key', true) }}"
# The path to the inventory.py file on the target-server.
inventory_py: "{{ ansible_user_dir }}/openshift-ansible/playbooks/openstack/inventory.py"
# The path to the openshift-ansible openshift-cluster directory.
openshift_cluster_directory: "{{ ansible_user_dir }}/openshift-ansible/playbooks/openstack/openshift-cluster"
# The path to the openshift-ansible openshift-node directory.
openshift_node_directory: "{{ ansible_user_dir }}/openshift-ansible/playbooks/openshift-node"
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
