---
# Rough equivalents of the Amazon ec2 flavors.
ec2_flavors:
  # https://aws.amazon.com/ec2/previous-generation/
  - { name: m1.small, vcpu: 1, memory: 1740, disk: 71 }
  - { name: m1.medium, vcpu: 1, memory: 3840, disk: 96 }
  - { name: m1.large, vcpu: 2, memory: 7680, disk: 128 }
  # https://aws.amazon.com/ec2/instance-types/#m4
  # The RAM values are reduced by 256 MB to fit better on hosts.
  - { name: m4.large, vcpu: 2, memory: "{{ 8192 - 256 }}", disk: 96 }
  - { name: m4.xlarge, vcpu: 4, memory: "{{ 16384 - 256 }}", disk: 96 }
  - { name: m4.2xlarge, vcpu: 8, memory: "{{ 32768 - 1280 }}", disk: 128 }
  - { name: m4.4xlarge, vcpu: 16, memory: "{{ 65536 - 256 }}", disk: 200 }
  - { name: m4.10xlarge, vcpu: 40, memory: "{{ 163840 - 256 }}", disk: 256 }
  # https://aws.amazon.com/ec2/instance-types/#r4
  # The RAM values are reduced by 256 MB to fit better on hosts.
  - { name: r4.large, vcpu: 2, memory: "{{ 15616 - 256 }}", disk: 71 }
  - { name: r4.xlarge, vcpu: 4, memory: "{{ 31232 - 256 }}", disk: 71 }
  - { name: r4.2xlarge, vcpu: 8, memory: "{{ 62464 - 256 }}", disk: 96 }
  - { name: r4.4xlarge, vcpu: 16, memory: "{{ 124928 - 256 }}", disk: 128 }
  - { name: r4.8xlarge, vcpu: 32, memory: "{{ 249856 - 256 }}", disk: 256 }
  - { name: r4.16xlarge, vcpu: 64, memory: "{{ 499712 - 256 }}", disk: 512 }
# The path to the OpenStack RC file on the openstack-server, may be named differently than other servers.
openstack_rc: "{{ ansible_user_dir }}/overcloudrc"
# The flavor property name and value to indicate the device for PCI passthrough.
pci_passthrough_property: '"pci_passthrough:alias"="nvme:1"'
