---
- name: pbench-agent image
  shell: podman pull docker.io/ravielluri/image:agent

- name: ensure that .kube dir exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.kube
    - /root/.kube

- name: copy the kubeconfig to a node
  copy:
    src: "{{playbook_dir}}/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config
  when:
    - KUBECONFIG_AUTH_DIR_PATH is undefined

# handle case where kubeconfig is in another specified dir
- name: copy the kubeconfig to controller node from specific directory
  copy:
    src: "{{ KUBECONFIG_AUTH_DIR_PATH }}/auth/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config
  when:
    - KUBECONFIG_AUTH_DIR_PATH is defined
    - KUBECONFIG_AUTH_DIR_PATH != ""

- name: ensure that ssh dir exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.ssh
    - /root/.ssh

- name: copy authorized keys
  copy:
    src: /home/core/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    remote_src: yes
    owner: root
    group: root

- name: copy perf private key to a node
  copy:
    src: "{{ansible_ssh_private_key_file}}"
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /home/core/.ssh/id_rsa
    - /root/.ssh/id_rsa
