---
# The version of ansible to install on the target server.
ansible_version: "{{ lookup('env', 'ansible_version')|default('2.6', true) }}"
# The path to the OpenStack RC file on the server vm, may be named differently than other servers.
openstack_rc: "{{ lookup('env', 'openstack_rc_path')|default(ansible_user_dir ~ '/keystonerc', true) }}"
# The boolean to control the cleaning of the yum cache.
clean_yum_cache: "{{ lookup('env', 'clean_yum_cache')|default(false, true) }}"
# A dictionary of packages to install for different families of operating systems.
packages:
  common:
    - bind
    - curl
    - gcc
    - git
    - jq
    - libselinux-python
    - redhat-rpm-config
    - python-crypto
    - sshpass
  Fedora:
    - python2-devel
    - python2-virtualenv
  CentOS:
    - epel-release
    - python-devel
    - python-virtualenv
  RedHat:
    - python-devel
    - python-virtualenv
  python:
    - "ansible=={{ ansible_version }}""
    - dnspython==1.15.0
    - Jinja2==2.10
    - jmespath==0.9.3
    - python-openstackclient==3.14.0
    - python-heatclient==1.14.0
    - shade==1.28.0
pip: pip
# When the virtualenv_directory is defined, a Python virtual environment is created.
# virtualenv_directory: virtualenv
